# syntax=docker/dockerfile:1
FROM inputoutput/cardano-node:latest

RUN mkdir -p /data/preview
RUN mkdir -p /data/preview/wallets
RUN mkdir -p /ipc

COPY ./preview-config/config.json /data/preview/config.json
COPY ./preview-config/topology.json /data/preview/topology.json
COPY ./preview-config/byron-genesis.json /data/preview/byron-genesis.json
COPY ./preview-config/shelley-genesis.json /data/preview/shelley-genesis.json
COPY ./preview-config/alonzo-genesis.json /data/preview/alonzo-genesis.json

ENV CARDANO_CONFIG=/data/preview/config.json
ENV CARDANO_TOPOLOGY=/data/preview/topology.json
ENV CARDANO_DATABASE_PATH=/data/preview/db
ENV CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
ENV WALLET_DIR=/data/preview/wallets
ENV TESTNET_MAGIC=2

COPY ./scripts/* /usr/local/bin/
RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["bash", "/usr/local/bin/entrypoint"]
