# syntax=docker/dockerfile:1
FROM inputoutput/cardano-node:latest

RUN mkdir -p /data/vasil-devnet
RUN mkdir -p /data/vasil-devnet/wallets
RUN mkdir -p /ipc

COPY ./vasil-devnet-config/config.json /data/vasil-devnet/config.json
COPY ./vasil-devnet-config/topology.json /data/vasil-devnet/topology.json
COPY ./vasil-devnet-config/byron-genesis.json /data/vasil-devnet/byron-genesis.json
COPY ./vasil-devnet-config/shelley-genesis.json /data/vasil-devnet/shelley-genesis.json
COPY ./vasil-devnet-config/alonzo-genesis.json /data/vasil-devnet/alonzo-genesis.json

ENV CARDANO_CONFIG=/data/vasil-devnet/config.json
ENV CARDANO_TOPOLOGY=/data/vasil-devnet/topology.json
ENV CARDANO_DATABASE_PATH=/data/vasil-devnet/db
ENV CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
ENV WALLET_DIR=/data/vasil-devnet/wallets
ENV TESTNET_MAGIC=9

COPY ./scripts/* /usr/local/bin/
RUN chmod +x /usr/local/bin/*

ENTRYPOINT ["bash", "/usr/local/bin/entrypoint"]
