#!/bin/bash

export CARDANO_CONFIG=/data/preview/config.json
export CARDANO_TOPOLOGY=/data/preview/topology.json
export CARDANO_DATABASE_PATH=/data/preview/db
export CARDANO_NODE_SOCKET_PATH=/ipc/node.socket

exec /usr/local/bin/cardano-node run --config $CARDANO_CONFIG --topology $CARDANO_TOPOLOGY --database-path $CARDANO_DATABASE_PATH --socket-path $CARDANO_NODE_SOCKET_PATH --host-addr 0.0.0.0 --port 3001
