#!/bin/bash

exec /usr/local/bin/cardano-node run \
	--config $CARDANO_CONFIG \
	--topology $CARDANO_TOPOLOGY \
	--database-path $CARDANO_DATABASE_PATH \
	--socket-path $CARDANO_NODE_SOCKET_PATH \
	--host-addr 0.0.0.0 \
	--port 3001
